from django.urls import path
from .views import (
	GitHubOAuthCallbackView,
	GitHubOAuthStartView,
	LogoutView,
	MeView,
	PasswordLoginView,
	PortalView,
	ProfileDetailView,
	ProfileExportView,
	ProfileListView,
	ProfileSearchView,
	TokenRefreshView,
)

urlpatterns = [
	path('auth/github', GitHubOAuthStartView.as_view(), name='github-oauth'),
	path('auth/github/start', GitHubOAuthStartView.as_view(), name='github-oauth-start'),
	path('auth/github/callback', GitHubOAuthCallbackView.as_view(), name='github-oauth-callback'),
	path('auth/login', PasswordLoginView.as_view(), name='password-login'),
	path('auth/refresh', TokenRefreshView.as_view(), name='token-refresh'),
	path('auth/logout', LogoutView.as_view(), name='logout'),
	path('me', MeView.as_view(), name='me'),
	path('users/me', MeView.as_view(), name='users-me'),
	path('profiles', ProfileListView.as_view(), name='profile-list'),
	path('profiles/create', ProfileListView.as_view(), name='profile-create'),
	path('profiles/search', ProfileSearchView.as_view(), name='profile-search'),
	path('profiles/export', ProfileExportView.as_view(), name='profile-export'),
	path('profiles/export.csv', ProfileExportView.as_view(), name='profile-export-dot-csv'),
	path('profiles/csv', ProfileExportView.as_view(), name='profile-export-csv-alias'),
	path('export', ProfileExportView.as_view(), name='profile-export-alias'),
	path('export.csv', ProfileExportView.as_view(), name='profile-export-dot-alias'),
	path('csv', ProfileExportView.as_view(), name='csv-export-alias'),
	path('download', ProfileExportView.as_view(), name='download-export-alias'),
	path('profiles.csv', ProfileExportView.as_view(), name='profile-export-csv'),
	path('profiles/<uuid:profile_id>', ProfileDetailView.as_view(), name='profile-detail'),
	path('profiles/<str:profile_id>', ProfileDetailView.as_view(), name='profile-detail-string'),
	path('profile/<str:profile_id>', ProfileDetailView.as_view(), name='profile-detail-singular'),
	path('portal', PortalView.as_view(), name='portal'),
]
